const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);let state=TDStore.load();
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function img(url,cls='',alt=''){return url?`<img class="${cls}" loading="lazy" src="${esc(url)}" alt="${esc(alt)}">`:''}
function render(){const p=state.profile;$('#name').textContent=p.name;$('#bio').textContent=p.bio;$('#avatar').src=p.avatar_url||'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="300" height="300"><rect width="100%" height="100%" fill="#e2e8f0"/><text x="50%" y="55%" text-anchor="middle" font-size="92" font-family="Arial" fill="#64748b">HTD</text></svg>`);$('#cover').style.backgroundImage=p.cover_url?`url("${p.cover_url}")`:'';$('#skills').innerHTML=(p.skills||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join('');const links=[];if(p.website)links.push(`<a href="${esc(p.website)}" target="_blank" rel="noopener">Website ↗</a>`);if(p.youtube)links.push(`<a href="${esc(p.youtube)}" target="_blank" rel="noopener">YouTube ↗</a>`);(p.custom_links||[]).forEach(link=>{if(link&&link.name&&link.url)links.push(`<a href="${esc(link.url)}" target="_blank" rel="noopener">${esc(link.name)} ↗</a>`)});Object.entries(p.social_links||{}).forEach(([k,v])=>{if(v&&!((p.custom_links||[]).some(link=>link.name===k&&link.url===v)))links.push(`<a href="${esc(v)}" target="_blank" rel="noopener">${esc(k)} ↗</a>`)});$('#links').innerHTML=links.join('');$('#aboutText').textContent=p.about||p.bio;$('#interests').textContent=p.interests||'—';$('#goals').textContent=p.goals||'—';renderPosts();renderProjects();renderMedia()}
function renderPosts(){const el=$('#postFeed');const posts=state.posts.filter(x=>x.status==='published').sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));if(!posts.length){el.innerHTML='<div class="empty">No published posts yet.</div>';return}el.innerHTML=posts.map(x=>`<article class="post">${x.cover_url?img(x.cover_url):''}<div class="post-body"><div class="meta">${esc(x.category||'Post')} · ${new Date(x.created_at).toLocaleDateString()}</div><h3>${esc(x.title)}</h3><p>${esc(x.content).slice(0,420)}${x.content.length>420?'…':''}</p><div class="project-actions" style="margin-top:14px"><a class="ghost" href="post.html?slug=${encodeURIComponent(x.slug)}">Read post</a></div></div></article>`).join('')}
function renderProjects(){const el=$('#projectGrid');const ps=state.projects.filter(x=>!x.hidden).sort((a,b)=>(b.featured-a.featured)||(a.sort_order-b.sort_order));if(!ps.length){el.innerHTML='<div class="empty">No projects yet.</div>';return}el.innerHTML=ps.map(x=>`<article class="project">${x.thumbnail_url?img(x.thumbnail_url):''}<div class="project-body"><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p><div class="tags">${(x.technologies||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="project-actions">${x.project_url?`<a class="primary" href="${esc(x.project_url)}" target="_blank" rel="noopener">View Project ↗</a>`:''}${x.github_url?`<a class="ghost" href="${esc(x.github_url)}" target="_blank" rel="noopener">GitHub ↗</a>`:''}</div></div></article>`).join('')}
function renderMedia(){const el=$('#mediaGrid');if(!state.media.length){el.innerHTML='<div class="empty">No public media yet.</div>';return}el.innerHTML=state.media.map(m=>`<div class="media-item"><img src="${esc(m.url)}" alt="${esc(m.filename||'Media')}" loading="lazy"></div>`).join('')}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.target).scrollIntoView({behavior:'smooth'})});
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.theme=document.body.classList.contains('dark')?'dark':'light'};if(localStorage.theme==='dark')document.body.classList.add('dark');
$('#shareBtn').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('Profile link copied')}catch{toast(location.href)}};
$('#searchBtn').onclick=()=>{$('#searchModal').classList.remove('hidden');$('#searchInput').focus()};$('#closeSearch').onclick=()=>$('#searchModal').classList.add('hidden');
$('#searchInput').oninput=e=>{const q=e.target.value.trim().toLowerCase();if(!q){$('#searchResults').innerHTML='';return}const posts=state.posts.filter(x=>x.status==='published'&&(`${x.title} ${x.content} ${(x.tags||[]).join(' ')}`.toLowerCase().includes(q)));const projects=state.projects.filter(x=>!x.hidden&&(`${x.name} ${x.description} ${(x.technologies||[]).join(' ')}`.toLowerCase().includes(q)));$('#searchResults').innerHTML=`<div style="margin-top:18px"><h3>Posts</h3>${posts.map(x=>`<p><a href="post.html?slug=${encodeURIComponent(x.slug)}">${esc(x.title)}</a></p>`).join('')||'<p class="meta">No results.</p>'}<h3>Projects</h3>${projects.map(x=>`<p>${esc(x.name)}</p>`).join('')||'<p class="meta">No results.</p>'}</div>`};
render();
